const fishdata = [
  {
    Name: "Fischerei",
    Nummer: 1710483,
    "Gehört zu Nummer": 0,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.4994772,
    Long: 13.4612654,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_3.jpg",
    Adresse: "Corinthstraße 51",
    PLZ: 10245,
    Stadt: "Berlin",
    Telefon: 497324653723,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/zieRvd3F6d42BbST7",
    Fischerei: true,
    Räucherei: true,
    Teichwirtschaft: false,
    Aquakultur: false,
    "Eigener Fang": true,
    "Regionaler Fang": false,
    Küstenfischerei: true,
    Binnenfischerei: false,
    Restaurant: true,
    Museum: false,
    Händler: false,
    Imbiss: false,
    Direktverkauf: true,
    Fischbrötchen: true,
    Räucherfisch: true,
    Aal: true,
    Forelle: false,
    Saibling: true,
    Karpfen: true,
    Stör: false,
    Wels: false,
    Hecht: true,
    Zander: false,
    Kaviar: false,
    Krabben: false,
    Krebs: false,
    Algen: false,
    Onlineshop: false,
    Beherbergung: true,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: true,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    "goldener Seestern": true,
    Bewertung: 0,
  },
  {
    Name: "Fischerei - Verkaufswagen",
    Nummer: 1710484,
    "Gehört zu Nummer": 1710483,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.5081661,
    Long: 13.4625695,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_4.jpg",
    Adresse: "Wühlischstraße 49",
    PLZ: 10245,
    Stadt: "Berlin",
    Telefon: 498579039929,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/rTVyRRmuHuMdtxpy6",
    Fischerei: true,
    Räucherei: true,
    Teichwirtschaft: false,
    Aquakultur: false,
    "Eigener Fang": true,
    "Regionaler Fang": false,
    Küstenfischerei: true,
    Binnenfischerei: false,
    Restaurant: false,
    Museum: false,
    Händler: false,
    Imbiss: false,
    Direktverkauf: true,
    Fischbrötchen: false,
    Räucherfisch: true,
    Aal: true,
    Forelle: false,
    Saibling: true,
    Karpfen: true,
    Stör: false,
    Wels: false,
    Hecht: true,
    Zander: false,
    Kaviar: false,
    Krabben: false,
    Krebs: false,
    Algen: false,
    Onlineshop: false,
    Beherbergung: false,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: false,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    "goldener Seestern": true,
    Bewertung: 0,
  },
  {
    Name: "Fischerei - Marktstand",
    Nummer: 1710485,
    "Gehört zu Nummer": 1710483,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.511295,
    Long: 13.425452,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_1.jpg",
    Adresse: "Spree 12",
    PLZ: 10119,
    Stadt: "Berlin",
    Telefon: 491293884485,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/8qCrMPLK4mgR1UWX8",
    Fischerei: true,
    Räucherei: true,
    Teichwirtschaft: false,
    Aquakultur: false,
    "Eigener Fang": true,
    "Regionaler Fang": false,
    Küstenfischerei: true,
    Binnenfischerei: false,
    Restaurant: false,
    Museum: false,
    Händler: false,
    Imbiss: true,
    Direktverkauf: true,
    Fischbrötchen: true,
    Räucherfisch: true,
    Aal: true,
    Forelle: false,
    Saibling: true,
    Karpfen: true,
    Stör: false,
    Wels: false,
    Hecht: true,
    Zander: false,
    Kaviar: false,
    Krabben: false,
    Krebs: false,
    Algen: false,
    Onlineshop: false,
    Beherbergung: false,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: false,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    "goldener Seestern": true,
    Bewertung: 0,
  },
  {
    Name: "Aquakultur Aquatik",
    Nummer: 1710486,
    "Gehört zu Nummer": 0,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.463059,
    Long: 12.861004,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_3.jpg",
    Adresse: "Corinthstraße 51",
    PLZ: 16458,
    Stadt: "Brandenburg",
    Telefon: 497324653723,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/zieRvd3F6d42BbST7",
    Fischerei: false,
    Räucherei: false,
    Teichwirtschaft: true,
    Aquakultur: true,
    "Eigener Fang": false,
    "Regionaler Fang": true,
    Küstenfischerei: false,
    Binnenfischerei: false,
    Restaurant: false,
    Museum: false,
    Händler: true,
    Imbiss: false,
    Direktverkauf: true,
    Fischbrötchen: false,
    Räucherfisch: false,
    Aal: true,
    Forelle: true,
    Saibling: false,
    Karpfen: false,
    Stör: true,
    Wels: false,
    Hecht: false,
    Zander: false,
    Kaviar: true,
    Krabben: false,
    Krebs: false,
    Algen: false,
    Onlineshop: true,
    Beherbergung: false,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: false,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    "goldener Seestern": false,
    Bewertung: 0,
  },
  {
    Name: "Aquakultur Aquatik am Aquaberg",
    Nummer: 1710487,
    "Gehört zu Nummer": 1710486,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.608285,
    Long: 13.577639,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_4.jpg",
    Adresse: "Wühlischstraße 49",
    PLZ: 16438,
    Stadt: "Brandenburg",
    Telefon: 498579039929,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/rTVyRRmuHuMdtxpy6",
    Fischerei: false,
    Räucherei: false,
    Teichwirtschaft: true,
    Aquakultur: true,
    "Eigener Fang": false,
    "Regionaler Fang": true,
    Küstenfischerei: false,
    Binnenfischerei: false,
    Restaurant: false,
    Museum: false,
    Händler: true,
    Imbiss: false,
    Direktverkauf: true,
    Fischbrötchen: false,
    Räucherfisch: false,
    Aal: true,
    Forelle: true,
    Saibling: false,
    Karpfen: false,
    Stör: true,
    Wels: false,
    Hecht: false,
    Zander: false,
    Kaviar: true,
    Krabben: false,
    Krebs: false,
    Algen: false,
    Onlineshop: true,
    Beherbergung: false,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: false,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    "goldener Seestern": false,
    Bewertung: 0,
  },
  {
    Name: "Aquakultur Aquatik Marktstand",
    Nummer: 1710488,
    "Gehört zu Nummer": 1710488,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.678409,
    Long: 13.268693,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_1.jpg",
    Adresse: "Spree 12",
    PLZ: 16489,
    Stadt: "Brandenburg",
    Telefon: 491293884485,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/8qCrMPLK4mgR1UWX8",
    Fischerei: false,
    Räucherei: false,
    Teichwirtschaft: true,
    Aquakultur: true,
    "Eigener Fang": false,
    "Regionaler Fang": true,
    Küstenfischerei: false,
    Binnenfischerei: false,
    Restaurant: false,
    Museum: false,
    Händler: true,
    Imbiss: true,
    Direktverkauf: true,
    Fischbrötchen: true,
    Räucherfisch: false,
    Aal: true,
    Forelle: true,
    Saibling: false,
    Karpfen: false,
    Stör: true,
    Wels: false,
    Hecht: false,
    Zander: false,
    Kaviar: true,
    Krabben: false,
    Krebs: false,
    Algen: false,
    Onlineshop: true,
    Beherbergung: false,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: false,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    "goldener Seestern": false,
    Bewertung: 0,
  },
  {
    Name: "Restaurant und Übernachtung",
    Nummer: 1710489,
    "Gehört zu Nummer": 1710489,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.304878,
    Long: 13.254073,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_1.jpg",
    Adresse: "Spree 12",
    PLZ: 14974,
    Stadt: "Ludwigsfelde",
    Telefon: 491293884485,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/8qCrMPLK4mgR1UWX8",
    Fischerei: false,
    Räucherei: false,
    Teichwirtschaft: false,
    Aquakultur: false,
    "Eigener Fang": false,
    "Regionaler Fang": true,
    Küstenfischerei: false,
    Binnenfischerei: false,
    Restaurant: true,
    Museum: false,
    Händler: false,
    Imbiss: true,
    Direktverkauf: false,
    Fischbrötchen: true,
    Räucherfisch: true,
    Aal: false,
    Forelle: false,
    Saibling: true,
    Karpfen: true,
    Stör: false,
    Wels: false,
    Hecht: false,
    Zander: false,
    Kaviar: false,
    Krabben: false,
    Krebs: false,
    Algen: true,
    Onlineshop: true,
    Beherbergung: true,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: true,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    "goldener Seestern": false,
    Bewertung: 0,
  },
];
