const fishdatamvp = [
  {
    Name: "Fischerei",
    Nummer: 1710483,
    "Gehört zu Nummer": 0,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.4994772,
    Long: 13.4612654,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_3.jpg",
    Adresse: "Corinthstraße 51",
    PLZ: 10245,
    Stadt: "Berlin",
    Telefon: 497324653723,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/zieRvd3F6d42BbST7",
    Fischerei: true,
    Küstenfischerei: true,
    Binnenfischerei: false,
    Fischzucht: false,
    Teichwirtschaft: false,
    Aquakultur: false,
    Räucherei: true,
    Händler: false,
    Gastronomie: true,
    Restaurant: true,
    Imbiss: false,
    Kultur: false,
    Direktverkauf: true,
    Onlineshop: false,
    "goldener Seestern": true,
    "Eigener Fang": true,
    "Regionaler Fang": false,
    Museum: false,
    Fischbrötchen: true,
    Räucherfisch: true,
    Aal: true,
    Algen: false,
    Forelle: false,
    Hecht: true,
    Karpfen: true,
    Wels: false,
    Kaviar: false,
    Krabben: false,
    Krebs: false,
    Saibling: true,
    Stör: false,
    Zander: false,
    Beherbergung: true,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: true,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    Bewertung: 0,
  },
  {
    Name: "Fischerei - Verkaufswagen",
    Nummer: 1710484,
    "Gehört zu Nummer": 1710483,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.5081661,
    Long: 13.4625695,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_4.jpg",
    Adresse: "Wühlischstraße 49",
    PLZ: 10245,
    Stadt: "Berlin",
    Telefon: 498579039929,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/rTVyRRmuHuMdtxpy6",
    Fischerei: true,
    Küstenfischerei: false,
    Binnenfischerei: true,
    Fischzucht: false,
    Teichwirtschaft: false,
    Aquakultur: false,
    Räucherei: true,
    Händler: false,
    Gastronomie: false,
    Restaurant: false,
    Imbiss: false,
    Kultur: false,
    Direktverkauf: true,
    Onlineshop: false,
    "goldener Seestern": true,
    "Eigener Fang": true,
    "Regionaler Fang": false,
    Museum: false,
    Fischbrötchen: false,
    Räucherfisch: true,
    Aal: true,
    Algen: false,
    Forelle: false,
    Hecht: true,
    Karpfen: true,
    Wels: false,
    Kaviar: false,
    Krabben: false,
    Krebs: false,
    Saibling: true,
    Stör: false,
    Zander: false,
    Beherbergung: false,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: false,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    Bewertung: 0,
  },
  {
    Name: "Fischerei - Marktstand",
    Nummer: 1710485,
    "Gehört zu Nummer": 1710483,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.511295,
    Long: 13.425452,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_1.jpg",
    Adresse: "Spree 12",
    PLZ: 10119,
    Stadt: "Berlin",
    Telefon: 491293884485,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/8qCrMPLK4mgR1UWX8",
    Fischerei: true,
    Küstenfischerei: true,
    Binnenfischerei: false,
    Fischzucht: false,
    Teichwirtschaft: false,
    Aquakultur: false,
    Räucherei: true,
    Händler: false,
    Gastronomie: true,
    Restaurant: false,
    Imbiss: true,
    Kultur: false,
    Direktverkauf: true,
    Onlineshop: false,
    "goldener Seestern": true,
    "Eigener Fang": true,
    "Regionaler Fang": false,
    Museum: false,
    Fischbrötchen: true,
    Räucherfisch: true,
    Aal: true,
    Algen: false,
    Forelle: false,
    Hecht: true,
    Karpfen: true,
    Wels: false,
    Kaviar: false,
    Krabben: false,
    Krebs: false,
    Saibling: true,
    Stör: false,
    Zander: false,
    Beherbergung: false,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: false,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    Bewertung: 0,
  },
  {
    Name: "Aquakultur Aquatik",
    Nummer: 1710486,
    "Gehört zu Nummer": 0,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.463059,
    Long: 12.861004,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_3.jpg",
    Adresse: "Corinthstraße 51",
    PLZ: 16458,
    Stadt: "Brandenburg",
    Telefon: 497324653723,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/zieRvd3F6d42BbST7",
    Fischerei: false,
    Küstenfischerei: false,
    Binnenfischerei: false,
    Fischzucht: true,
    Teichwirtschaft: true,
    Aquakultur: false,
    Räucherei: false,
    Händler: true,
    Gastronomie: false,
    Restaurant: false,
    Imbiss: false,
    Kultur: false,
    Direktverkauf: true,
    Onlineshop: true,
    "goldener Seestern": false,
    "Eigener Fang": false,
    "Regionaler Fang": true,
    Museum: false,
    Fischbrötchen: false,
    Räucherfisch: false,
    Aal: true,
    Algen: false,
    Forelle: true,
    Hecht: false,
    Karpfen: false,
    Wels: false,
    Kaviar: true,
    Krabben: false,
    Krebs: false,
    Saibling: false,
    Stör: true,
    Zander: false,
    Beherbergung: false,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: false,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    Bewertung: 0,
  },
  {
    Name: "Aquakultur Aquatik am Aquaberg",
    Nummer: 1710487,
    "Gehört zu Nummer": 1710486,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.608285,
    Long: 13.577639,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_4.jpg",
    Adresse: "Wühlischstraße 49",
    PLZ: 16438,
    Stadt: "Brandenburg",
    Telefon: 498579039929,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/rTVyRRmuHuMdtxpy6",
    Fischerei: false,
    Küstenfischerei: false,
    Binnenfischerei: false,
    Fischzucht: true,
    Teichwirtschaft: false,
    Aquakultur: true,
    Räucherei: false,
    Händler: true,
    Gastronomie: false,
    Restaurant: false,
    Imbiss: false,
    Kultur: false,
    Direktverkauf: true,
    Onlineshop: true,
    "goldener Seestern": false,
    "Eigener Fang": false,
    "Regionaler Fang": true,
    Museum: false,
    Fischbrötchen: false,
    Räucherfisch: false,
    Aal: true,
    Algen: false,
    Forelle: true,
    Hecht: false,
    Karpfen: false,
    Wels: false,
    Kaviar: true,
    Krabben: false,
    Krebs: false,
    Saibling: false,
    Stör: true,
    Zander: false,
    Beherbergung: false,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: false,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    Bewertung: 0,
  },
  {
    Name: "Aquakultur Aquatik Marktstand",
    Nummer: 1710488,
    "Gehört zu Nummer": 1710488,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.678409,
    Long: 13.268693,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_1.jpg",
    Adresse: "Spree 12",
    PLZ: 16489,
    Stadt: "Brandenburg",
    Telefon: 491293884485,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/8qCrMPLK4mgR1UWX8",
    Fischerei: false,
    Küstenfischerei: false,
    Binnenfischerei: false,
    Fischzucht: true,
    Teichwirtschaft: true,
    Aquakultur: false,
    Räucherei: false,
    Händler: true,
    Gastronomie: true,
    Restaurant: false,
    Imbiss: true,
    Kultur: false,
    Direktverkauf: true,
    Onlineshop: true,
    "goldener Seestern": false,
    "Eigener Fang": false,
    "Regionaler Fang": true,
    Museum: false,
    Fischbrötchen: true,
    Räucherfisch: false,
    Aal: true,
    Algen: false,
    Forelle: true,
    Hecht: false,
    Karpfen: false,
    Wels: false,
    Kaviar: true,
    Krabben: false,
    Krebs: false,
    Saibling: false,
    Stör: true,
    Zander: false,
    Beherbergung: false,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: false,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    Bewertung: 0,
  },
  {
    Name: "Restaurant und Übernachtung",
    Nummer: 1710489,
    "Gehört zu Nummer": 1710489,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.304878,
    Long: 13.254073,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_1.jpg",
    Adresse: "Spree 12",
    PLZ: 14974,
    Stadt: "Ludwigsfelde",
    Telefon: 491293884485,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/8qCrMPLK4mgR1UWX8",
    Fischerei: false,
    Küstenfischerei: false,
    Binnenfischerei: false,
    Fischzucht: false,
    Teichwirtschaft: false,
    Aquakultur: false,
    Räucherei: false,
    Händler: false,
    Gastronomie: true,
    Restaurant: true,
    Imbiss: true,
    Kultur: false,
    Direktverkauf: false,
    Onlineshop: true,
    "goldener Seestern": false,
    "Eigener Fang": false,
    "Regionaler Fang": true,
    Museum: false,
    Fischbrötchen: true,
    Räucherfisch: true,
    Aal: false,
    Algen: true,
    Forelle: false,
    Hecht: false,
    Karpfen: true,
    Wels: false,
    Kaviar: false,
    Krabben: false,
    Krebs: false,
    Saibling: true,
    Stör: false,
    Zander: false,
    Beherbergung: true,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: true,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    Bewertung: 0,
  },
  {
    Name: "Museum der Fischerei",
    Nummer: 1710490,
    "Gehört zu Nummer": 0,
    Ausschließen: false,
    Verifiziert: false,
    Lat: 52.50868,
    Long: 13.291095,
    Beschreibung:
      "Eine unvollständige und sich ständig erweiternde Karte. Gedacht als Übersicht über die letzten heimischen, traditionellen Fischereibetriebe und ihre Verkaufsstellen. Aus dem Antrieb, regionalen, qualitativ hochwertigen, frischen Fisch zur eigenen Zubereitung zu finden.",
    Bild: "https://thelastfishermap.com/img/image_4.jpg",
    Adresse: "Wundtstraße 40",
    PLZ: 14057,
    Stadt: "Berlin",
    Telefon: 491293884485,
    "E-Mail": "info@thelastfishermap.com",
    Webseite: "thelastfishermap.com",
    Instagram: "instagram.com/thelastfishermap",
    Facebook: "facebook.com/thelastfishermap",
    "Googlemaps Link": "https://maps.app.goo.gl/y6iEQTKjFDC972Go6",
    Fischerei: false,
    Küstenfischerei: false,
    Binnenfischerei: false,
    Fischzucht: false,
    Teichwirtschaft: false,
    Aquakultur: false,
    Räucherei: false,
    Händler: false,
    Gastronomie: false,
    Restaurant: false,
    Imbiss: false,
    Kultur: true,
    Direktverkauf: false,
    Onlineshop: false,
    "goldener Seestern": false,
    "Eigener Fang": false,
    "Regionaler Fang": false,
    Museum: true,
    Fischbrötchen: false,
    Räucherfisch: false,
    Aal: false,
    Algen: false,
    Forelle: false,
    Hecht: false,
    Karpfen: false,
    Wels: false,
    Kaviar: false,
    Krabben: false,
    Krebs: false,
    Saibling: false,
    Stör: false,
    Zander: false,
    Beherbergung: false,
    Gästefahrten: false,
    Charter: false,
    Seebestattung: false,
    Angeln: false,
    Liegeplätze: false,
    Nachhaltig: false,
    MSC: false,
    Besucht: false,
    Bewertung: 0,
  },
];
